# Welcome to Jekyll!
#
# This config file contains settings for your portfolio site built with Jekyll.

# ==========================================================
# Site settings
# ==========================================================
theme: jekyll-theme-so-simple
skin: "/assets/css/skins/default.css"
locale: en-US
title: "Griffin Schultz Design Portfolio"
description: "Welcome to my design portfolio — a showcase of CAD, simulation, and fabrication projects demonstrating my skills in SolidWorks, FEA analysis, and product design."

# GitHub Pages settings
url: "https://gss17.github.io"   # Your GitHub Pages root
baseurl: "/myDesignJekyll"       # Repo name — must start with a slash

logo:                            # Optional: path to site logo, e.g. "/images/logo.png"
date_format: "%Y"

# Optional site features
read_time:                       # e.g. true to enable read times
words_per_minute:                # e.g. 200
mathjax:
  enable:
  combo:
  tags:

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

google_analytics:
disqus:
  shortname:
twitter:
  username:

# ==========================================================
# Liquid
# ==========================================================
liquid:
  error_mode: strict

# ==========================================================
# Build settings
# ==========================================================
permalink: /:categories/:title/
markdown: kramdown

feed:
  path: atom.xml

# ==========================================================
# Pagination
# ==========================================================
# paginate: 10
# paginate_path: /page:num/

# ==========================================================
# Search
# ==========================================================
search_full_content: false

# ==========================================================
# Plugins
# ==========================================================
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# ==========================================================
# Front Matter Defaults
# ==========================================================
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# ==========================================================
# Site Author
# ==========================================================
author:
  name: Griffin Schultz
  picture:
  email:
  links:
    - title: LinkedIn
      url: https://www.linkedin.com/in/griffin-schultz-770b12185/
      icon: fab fa-linkedin

# ==========================================================
# Footer Links
# ==========================================================
footer_links:
  - title: LinkedIn
    url: https://www.linkedin.com/in/griffin-schultz-770b12185/
    icon: fab fa-linkedin
exclude:
  - CHANGELOG.md
  - README.md
  - README-OLD.md
  - Rakefile
  - package.json
  - package-lock.json
  - node_modules
